- name: get tower hosts
  hosts: localhost
  connection: local
  vars:
    students_count: 7
    students_vm_count: 3
  tasks:
    - name: install dependencies
      pip:
        name: ansible-tower-cli

    - name: get data
      tower_receive:
        inventory:
         - all
      register: tower_data

    - name: create students vms list
      block:
        - name: default dict
          loop: "{{ range(1, students_count + 1, 1) | list }}"
          set_fact:
            students: "{{ students | default([]) + ['student0' + item|string] }}"

        - name: set
          loop: "{{ students }}"
          set_fact:
            students_vms: "{{ students_vms | default([]) + [ item + '-vm1', item + '-vm2', item + '-vm3' ] }}"
    
    - name: find ip for vm
      loop: "{{ tower_data.assets[0].asset_relation.group }}"
      when: "item.name in students_vms"
      set_fact:
        students_dict: "{{ students_dict | default([]) + [{ 'name': item.name, 'ip': item.hosts[0]}]}}"

    - name: debug
      debug:
        msg: "{{ students_dict }}"

    - name: create index.html
      template:
        src: templates/index.html.j2
        dest: ansibe-vm-list/index.html

    - name: build container
      docker_image:
        name: ansible-training-vm-list:latest
        source: build
        build:
          path: ansibe-vm-list
          pull: true
